export const data = [
  {
    id: 1,
    img: "productImg/img1.jpg",
    title: "Nike Air Max 270",
    star: 4.5,
    reviews: 1200,
    price: 150,
    company: "Nike",
    category: "Running",
  },
  {
    id: 2,
    img: "productImg/img2.jpg",
    title: "Nike Air Force 1",
    star: 4.7,
    reviews: 2500,
    price: 100,
    company: "Nike",
    category: "Casual",
  },
  {
    id: 3,
    img: "productImg/img3.jpg",
    title: "Nike React Infinity Run",
    star: 4.6,
    reviews: 1800,
    price: 160,
    company: "Nike",
    category: "Running",
  },
  {
    id: 4,
    img: "productImg/img4.jpg",
    title: "Adidas Superstar",
    star: 4.8,
    reviews: 2800,
    price: 100,
    company: "Adidas",
    category: "Casual",
  },
  {
    id: 5,
    img: "productImg/img5.jpg",
    title: "Adidas Terrex Swift",
    star: 4.4,
    reviews: 800,
    price: 130,
    company: "Adidas",
    category: "Hiking",
  },
  {
    id: 6,
    img: "productImg/img6.jpg",
    title: "Puma RS-X",
    star: 4.5,
    reviews: 1100,
    price: 110,
    company: "Puma",
    category: "Casual",
  },
  {
    id: 7,
    img: "productImg/img7.jpg",
    title: "Puma Cali Sport",
    star: 4.6,
    reviews: 1300,
    price: 100,
    company: "Puma",
    category: "Casual",
  },
  {
    id: 8,
    img: "productImg/img8.jpg",
    title: "Puma Ignite Flash",
    star: 4.4,
    reviews: 900,
    price: 120,
    company: "Puma",
    category: "Running",
  },
  {
    id: 9,
    img: "productImg/img9.jpg",
    title: "Puma Smash V2",
    star: 4.7,
    reviews: 1400,
    price: 80,
    company: "Puma",
    category: "Casual",
  },
  {
    id: 10,
    img: "productImg/img10.jpg",
    title: "Sparx SD-028",
    star: 4.1,
    reviews: 500,
    price: 45,
    company: "Sparx",
    category: "Sports",
  },
  {
    id: 11,
    img: "productImg/img11.jpg",
    title: "Adidas Pureboost",
    star: 4.5,
    reviews: 1200,
    price: 160,
    company: "Adidas",
    category: "Running",
  },
  {
    id: 12,
    img: "productImg/img12.jpg",
    title: "Sparx SM-501",
    star: 4.2,
    reviews: 600,
    price: 50,
    company: "Sparx",
    category: "Casual",
  },
  {
    id: 13,
    img: "productImg/img13.jpg",
    title: "Sparx SD-045",
    star: 4.4,
    reviews: 750,
    price: 55,
    company: "Sparx",
    category: "Sports",
  },
];
